### ISSUE TITLE
Build and run 'linux' test application

### ISSUE THREAD

**Issue by nicomgd** [mgdesign-fr/mapbox-gl-native#7]

**Comment by jf-mgd** [comment]
Wunderbar!
![image](https://cloud.githubusercontent.com/assets/13003125/9605515/6923ce04-50be-11e5-890e-2a2633ebcfd6.png)

**Comment by jf-mgd** [comment]
Uncommited changes to make sample working:
- Modify paths in `platform/default/default_styles.cpp`
- Add token key to environment variables.
